//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Escuela_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MateriaFacultad
    {
        public int ID_MateriaFacultad { get; set; }
        public int materia { get; set; }
        public int facultad { get; set; }
    
        public virtual Facultad Facultad1 { get; set; }
        public virtual Materia Materia1 { get; set; }
    }
}
